# Generated by Django 3.2.12 on 2022-04-28 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e93f19d0-3f7e-476b-a091-980f8037a3bf'), primary_key=True, serialize=False),
        ),
    ]
