# Generated by Django 3.2.12 on 2022-06-10 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220610_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('85de6a90-a9ca-4ffb-ba5c-54af771d34d9'), primary_key=True, serialize=False),
        ),
    ]
