# Generated by Django 3.2.12 on 2022-06-10 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9bf6de2a-01b3-44e6-b658-9f510b55ab9f'), primary_key=True, serialize=False),
        ),
    ]
