# Generated by Django 3.2.12 on 2022-06-10 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ce0b75ba-81b8-4cd5-a6e1-3b33e9cc5c64'), primary_key=True, serialize=False),
        ),
    ]
