# Generated by Django 3.2.12 on 2022-06-10 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('73be13f1-6f32-4e0e-8287-b328b4f43346'), primary_key=True, serialize=False),
        ),
    ]
