# Generated by Django 3.2.12 on 2022-06-10 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6ff7d5b5-d36b-4817-b7f1-cb0cc795292c'), primary_key=True, serialize=False),
        ),
    ]
