# Generated by Django 3.2.12 on 2022-06-10 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8871f525-f93b-4d21-8089-1a0723e87038'), primary_key=True, serialize=False),
        ),
    ]
