# Generated by Django 3.2.12 on 2022-06-10 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('44e51ee3-37f6-4af5-aa65-23064cb194f7'), primary_key=True, serialize=False),
        ),
    ]
