# Generated by Django 3.2.12 on 2022-06-11 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('03eb1b13-3169-4197-b121-f9f150c2c996'), primary_key=True, serialize=False),
        ),
    ]
