# Generated by Django 3.2.12 on 2022-06-11 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_author_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('016728ed-7d01-44ce-a195-49865a38d4fb'), primary_key=True, serialize=False),
        ),
    ]
